expenses/urls.py
from . import views


from django.conf.urls import url


# SET THE NAMESPACE!
app_name = 'expenses'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^add/$',views.add,name='add'),
    url(r'^home/$',views.home,name='home'),
    url(r'^viewlist/$',views.viewlist,name='viewlist'),
    url(r'^(?P<p_k>\d+)/modify/', views.modify, name='modify'),
    url(r'^itemupdate/(?P<p_k>\d+)/', views.itemupdate, name='itemupdate'),
    url(r'^itemdelete/(?P<p_k>\d+)/$', views.itemdelete, name='itemdelete'),
    url(r'^logout/$', views.user_logout, name='logout'),
    ]

myproject/urls.py
from django.contrib import admin, auth
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.conf.urls import url,include
from expenses import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^expenses/',include('expenses.urls')),
]




if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class UserProfileInfo(models.Model):

   # user = models.OneToOneField(User,on_delete=models.CASCADE)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
   # password = models.OneToOneField(User,on_delete=models.CASCADE)
    
def __str__(self):
  return self.user.username

class Product(models.Model):
    p_k = models.AutoField(primary_key=True)
    item= models.TextField(max_length=2000)
    price= models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'static/expenses/',null=True, blank=True)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.item) + ": Rs" + str(self.price)

    def get_absolute_url(self):
        return reverse('itemupdate', kwargs={'pk': self.p_k})

expenses/forms.py
from django import forms
#from expenses.models import UserProfileInfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Product

"""class UserForm(forms.Form):
 username = forms.CharField(max_length=25)
 password = forms.CharField(widget=forms.PasswordInput())

class Meta():
  model = User
  fields = "__all__"

class UserProfileInfoForm(forms.ModelForm):
 
 class Meta():
  model = UserProfileInfo
  fields = "__all__" """


 
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class ExpenseUploadForm(forms.ModelForm):
    item = forms.CharField(max_length=30)
    price = forms.DecimalField()
    image = forms.ImageField(required=False)

    class Meta:
        model = Product
        fields = ('item','price','image', )

expenses/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.db.models.functions import Lower


# Create your views here.
from django.shortcuts import render, get_object_or_404
from expenses.forms import SignUpForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from expenses.forms import ExpenseUploadForm
from expenses.models import Product
from django.shortcuts import redirect
from django.views.generic import ListView
from django.db.models import Q




def index(request):
    return render(request,'index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        #user_form = UserForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            registered = True
        else:
            print("Errors are")
            print(form.errors)
    else:
        form = SignUpForm()
    return render(request,'registration.html',
                          {'form':form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                #return redirect('add')
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    #return redirect('index')
                    #return render(request, 'home.html', {})

                    return HttpResponseRedirect(reverse('expenses:home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})

@login_required
def home(request):
    query_results = Product.objects.all()
    total = 0
    for prod in query_results:
        total+=prod.price
    context={
            "query_results" : query_results,
            "total_expenses":total
        }
    return render(request,'home.html',context)

@login_required
def add(request):
    if request.method == 'POST':
        expense_form = ExpenseUploadForm(request.POST,request.FILES)
        #user_form = UserForm(data=request.POST)
        if expense_form.is_valid():
            expense_form.save()
            #p= Product.object.get(pk=item_id)
            item = expense_form.cleaned_data.get('item')
            price = expense_form.cleaned_data.get('price')
            #image = expense_form.cleaned_data.get('image')
            #p.save()

            return HttpResponseRedirect(reverse('expenses:viewlist'))
        
    else:
        form = ExpenseUploadForm()
    return render(request,'add.html',
                          {'ExpenseUploadForm':ExpenseUploadForm})

@login_required
def viewlist(request):
    query=request.GET.get("q")
    order_column=request.GET.get("o") or "p_k"
    query_results = Product.objects.all().order_by("%s"% order_column)
    if query:
        queryset_list = query_results.filter(
            Q(item__icontains=query) |
            Q(price__icontains=query)
            ).distinct()
        if queryset_list:
            context={
                "query_results":queryset_list,
            }
        else :
            print("No item found")
            return render(request,'search.html')
        
    else:
        total = 0
        for prod in query_results:
            total+=prod.price
        print(total)
        context={
            "query_results":query_results,
            "total_expenses":total
        }
    return render(request, 'viewlist.html', context)

@login_required
def itemupdate(request, p_k=None):
    instance = get_object_or_404(Product, p_k=p_k)
    expense_form = ExpenseUploadForm(request.POST,request.FILES,instance=instance)
    if expense_form.is_valid():
        expense_form.save()
        return HttpResponseRedirect(reverse('expenses:viewlist'))

    context={
        "item":instance.item,
        "instance":instance,
        'ExpenseUploadForm':ExpenseUploadForm,
    }

    return render(request,"update.html",context)

@login_required
def itemdelete(request, p_k=None):
    item= get_object_or_404(Product, p_k=p_k)    
    if item.delete():
        return HttpResponseRedirect(reverse('expenses:viewlist'))
    return render(request, 'item_confirm_delete.html',{'item':item})

@login_required
def modify(request,p_k=None):
    instance = get_object_or_404(Product, p_k=p_k)
    return render(request,'modify.html', {'instance': instance})

templates/expenses/add.html
{% extends "home.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if ExpensesAdded %}
        <h1>Thank you!</h1>
      {% else %}
        <h3>Please add your expenses</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ ExpenseUploadForm.as_p }}
          <input type="submit" name="" value="Submit">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/expenses/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'expenses:register' %}">Register</a></li>     
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'expenses:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'expenses:user_login' %}">Login</a></li>
          {% endif %}

</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/expenses/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

{# Django Home Link / Admin Link / Register Link#}
        <li><a class="navbar-link" href="{% url 'expenses:add' %}">Add Expenses</a></li>  
        <li><a class="navbar-link" href="{% url 'expenses:viewlist' %}">ViewExpenses</a></li>
        <li><a href="{% url 'expenses:logout' %}">Logout</a></li>
    

</ul>
      </div>
    </nav>
    <div class="container">
    
    {% block body_block %}
    <h3>Hello {{ user.username }}, Welcome to Expense Tracker</h3>
    {% if query_results %}
    <p>Your Total Expenses: {{ total_expenses }}</p>
    <table width="300">
        <tr>
            <!--<th scope="col"><a href="?o=p_k">SerialNo</a></th>-->
            <th scope="col">ItemName</a></th>
            <th scope="col">Price</a></th>
        </tr>
        {% for product in query_results %}
      
          <tr> 
              <td>{{ product.item }}</a></td>
              <td>{{ product.price }}</td>
          
          </tr>
    
        {% endfor %}
    </table>
    {% else %}
      <p>No Items added</p>
    {% endif %}
    
    {% endblock %}
    </div>
  </body>
</html>

templates/expenses/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the MyProject !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/expenses/item_confirm_delete.html
<h1>Item Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete {{ item }} ?
    <input type="submit" value="Submit" />
</form>

templates/expenses/login.html
{% extends 'base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>

<form method="post" action="{% url 'expenses:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password">
            {% if request.GET.next %}
                <input type="hidden" name="next" values="{{request.GET.next}}">
            {% endif %}
            <input type="submit" name="" value="Login">

</form>

</div>
  </div>
{% endblock %}

templates/expenses/modify.html
{% extends "home.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if ExpensesAdded %}
        <h1>Thank you!</h1>
      {% else %}
        <h3>Please update/delete your expense</h3>
        
          <li><a class="navbar-link" href="{% url 'expenses:itemupdate' p_k=instance.p_k %}">Update Expenses</a></li>  
          <li><a class="navbar-link" href="{% url 'expenses:itemdelete' p_k=instance.p_k %}">Delete Expenses</a></li>
        
        
        

          
        
        
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/expenses/registration.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>

<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/expenses/search.html
{% extends "home.html" %}
{% load static %}
{% load staticfiles %}

{% block body_block %}


<div class="container">
  <div class="jumbotron">
    
    
    

   

  
    <p>Item Not Found</p>


  </div>
</div>

{% endblock %}

templates/expenses/update.html
{% extends "home.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if ExpensesAdded %}
        <h1>Thank you!</h1>
      {% else %}
        <h3>Please update your expenses</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ ExpenseUploadForm.as_p }}
          <input type="submit" name="" value="Submit">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/expenses/viewlist.html
{% extends "home.html" %}
{% load static %}
{% load staticfiles %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">

        <head>
        <h3>Search </h3>
        <form method='GET' action=''>
        <input type='text' name='q' placeholder='Search by item or price' values='{{ request.GET.q }}' />
        <input type='submit' value='Search'/>
    
        
        </head>


    
    
    

   

    </form>
    {% if query_results %}
    <h3>Expenses Added (To Update/Delete Expenses click on ItemName)</h3>
    
    
    <table width="700">
      <tr>
          <!--<th scope="col"><a href="?o=p_k">SerialNo</a></th>-->
          <th scope="col"><a href="?o=item">ItemName</a></th>
          <th scope="col"><a href="?o=image">Image</a></th>
          <th scope="col"><a href="?o=price">Price</a></th>
          <th scope="col"><a href="?o=created_date">CreationDate</a></th>
      </tr>
      
      {% for product in query_results %}
      {% if product %}
      <tr> 
          <!--<td>{{ product.p_k }}</td>-->
          <td><a href='/expenses/{{ product.p_k }}/modify/'>{{ product.item }}</a></td>
          <!--<td>{% with 'static/expenses/'|add:product.image as image_static %}
                {% static image_static %}
              {% endwith %}</td>-->
          <td>
              {% if product.image %}
              <img src="/{{ product.image.url }}" alt="{{product.image}}" width="60px" height="60px" /></td>
              {% else %}
              <img src="" alt="{{product.image}}" /></td>
             {% endif %}
          <td>{{ product.price }}</td>
          <td>{{ product.created_date }}</td>
      </tr>
      {% else %}
        <p> No Item found</p>
      {% endif %}
      {% endfor %}
  </table>
  {% if total_expenses %}
    <p>Total Expenses: {{ total_expenses }}</p>
  {% endif %}
  {% else %}
      <p>No Items Found</p>
  {% endif %}
  </div>
</div>

{% endblock %}